
* Scraper
  Full simulation of Pandora with Flash enabled on server.
  This works.

** Python modules
*** selenium
*** pyvirtualdisplay
** x11 stuff
    xorg
    xserver-xorg
    xauth
    restart the server.
** Install flash on Ubuntu
   Navigate to Flash website and download tarball

   Installation instructions
-------------------------

Installing using the plugin tar.gz:
        o Unpack the plugin tar.gz and copy the files to the appropriate location.  
        o Save the plugin tar.gz locally and note the location the file was saved to.
        o Launch terminal and change directories to the location the file was saved to.
        o Unpack the tar.gz file.  Once unpacked you will see the following:
                + libflashplayer.so
                + /usr
        o Identify the location of the browser plugins directory, based on your Linux distribution and Firefox version
        o Copy libflashplayer.so to the appropriate browser plugins directory.  At the prompt type:
                + cp libflashlayer.so <BrowserPluginsLocation>
        o Copy the Flash Player Local Settings configurations files to the /usr directory.  At the prompt type:
                + sudo cp -r usr/* /usr


* Firefox web development
** Install XPath Viewer for Firefox
    To analyze XPaths
** Install Firebug for firefox 
    To procure XPaths



* Playlist Modifier
  Wrapper around Spotify binary for updating playlists. 

** Create a playlist
** Update a playlist
   If not created, create first.
   Add a song or list of songs from file.


